"""
guardrail.py — Hallucination detection and citation grounding.

Strategy
--------
After the LLM produces a response we run three checks:

1. Variant coverage  — every HGVS variant string found in the response must
   appear verbatim in at least one retrieved context chunk.

2. Phenotype coverage — every clinical term (HPO-like) in the response must
   appear in the retrieved contexts (case-insensitive substring match).

3. PMID coverage — every PMID cited in the response must actually exist in the
   retrieved metadata.  Invented PMIDs are flagged immediately.

The function `apply_guardrail` returns a GuardrailResult dataclass that the
caller can inspect and optionally surface to the user.
"""

import re
import logging
from dataclasses import dataclass, field
from typing import List, Dict, Set

log = logging.getLogger("guardrail")

# ── Regex patterns ────────────────────────────────────────────────────────────

# HGVS coding + protein variants
_VARIANT_RE = re.compile(
    r"(?:"
    r"c\.\d+[-+]?\d*[A-Za-z]>[A-Za-z]"  # c.5A>G
    r"|p\.[A-Z][a-z]{2}\d+[A-Z*][a-z]*"  # p.Met1Thr
    r"|p\.\([A-Z][a-z]{2}\d+[A-Z*][a-z]*\)"  # p.(Met1Thr)
    r")",
    re.IGNORECASE,
)

# PMIDs as cited in the LLM response: PMID:12345678 or [PMID: 12345678]
_PMID_RE = re.compile(r"\bPMID[:\s]+(\d{6,9})\b", re.IGNORECASE)

# Clinical / phenotype terms we care about most
_PHENOTYPE_HINTS = [
    "hypomyelination",
    "leukodystrophy",
    "white matter",
    "cerebellar atrophy",
    "nystagmus",
    "spasticity",
    "developmental delay",
    "intellectual disability",
    "hypotonia",
    "ataxia",
    "seizure",
    "epilepsy",
    "peripheral neuropathy",
    "cognitive impairment",
    "gait disturbance",
    "MRI",
]


@dataclass
class GuardrailResult:
    passed: bool  # True = no hallucinations detected
    unverified_variants: List[str] = field(default_factory=list)
    fabricated_pmids: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    summary: str = ""

    def to_dict(self) -> dict:
        return {
            "passed": self.passed,
            "unverified_variants": self.unverified_variants,
            "fabricated_pmids": self.fabricated_pmids,
            "warnings": self.warnings,
            "summary": self.summary,
        }


def _extract_variants(text: str) -> Set[str]:
    return set(_VARIANT_RE.findall(text))


def _extract_pmids(text: str) -> Set[str]:
    return set(_PMID_RE.findall(text))


def _context_corpus(contexts: List[Dict]) -> str:
    """Concatenate all retrieved chunk texts into one searchable string."""
    return " ".join(c.get("document", "") for c in contexts)


def _available_pmids(contexts: List[Dict]) -> Set[str]:
    return {str(c["metadata"].get("pmid", "")) for c in contexts}


# ─────────────────────────────────────────────────────────────────────────────
#  Public API
# ─────────────────────────────────────────────────────────────────────────────


def apply_guardrail(
    response_text: str,
    contexts: List[Dict],
) -> GuardrailResult:
    """
    Verify that every factual claim in *response_text* is grounded in one of
    the retrieved *contexts*.

    Parameters
    ----------
    response_text : str
        The raw text generated by the LLM.
    contexts : list[dict]
        Each dict must have keys  "document" (str)  and  "metadata" (dict).
        metadata must contain at least "pmid".

    Returns
    -------
    GuardrailResult
    """
    corpus = _context_corpus(contexts)
    available_pmids = _available_pmids(contexts)
    warnings: List[str] = []

    # ── 1. Variant verification ───────────────────────────────────────────────
    claimed_variants = _extract_variants(response_text)
    unverified: List[str] = []
    for var in claimed_variants:
        if var.lower() not in corpus.lower():
            unverified.append(var)
            warnings.append(
                f"Variant '{var}' appears in response but NOT in any retrieved source."
            )

    # ── 2. PMID verification ──────────────────────────────────────────────────
    cited_pmids = _extract_pmids(response_text)
    fabricated: List[str] = []
    for pmid in cited_pmids:
        if pmid not in available_pmids:
            fabricated.append(pmid)
            warnings.append(
                f"PMID {pmid} cited in response but NOT found in retrieved documents — "
                f"possible hallucination."
            )

    # ── 3. Soft phenotype check ───────────────────────────────────────────────
    for term in _phenotype_terms_in_response(response_text):
        if term.lower() not in corpus.lower():
            warnings.append(
                f"Phenotype term '{term}' mentioned in response but not in retrieved context."
            )

    passed = (not unverified) and (not fabricated)

    if passed:
        summary = "[PASS] All variants and PMIDs in the response are grounded in retrieved sources."
    else:
        parts = []
        if unverified:
            parts.append(f"{len(unverified)} unverified variant(s)")
        if fabricated:
            parts.append(f"{len(fabricated)} fabricated PMID(s)")
        summary = "[WARN] Guardrail FAILED -- " + "; ".join(parts) + "."

    result = GuardrailResult(
        passed=passed,
        unverified_variants=unverified,
        fabricated_pmids=fabricated,
        warnings=warnings,
        summary=summary,
    )

    if warnings:
        for w in warnings:
            log.warning(w)
    else:
        log.info("Guardrail passed — no hallucinations detected.")

    return result


def _phenotype_terms_in_response(text: str) -> List[str]:
    """Return phenotype hint terms that appear in the LLM response."""
    found = []
    lower = text.lower()
    for term in _PHENOTYPE_HINTS:
        if term.lower() in lower:
            found.append(term)
    return found
